services:
  sons-server:
    container_name: sons-server
    build: .
    image: chemineer/sons-of-the-forest-dedicated:latest
    #image: sons-of-the-forest-dedicated
    restart: always
    init: true
    ports:
      - "8766:8766/udp" # Game port
      - "27016:27016/udp" # Query port
      - "9700:9700/udp" # Blob sync port
    volumes:
      - ./userdata:/app/sonsoftheforest/userdata
